# Generated by Django 5.1.6 on 2025-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("google_identity_uid", models.CharField(db_index=True, max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("tenant_id", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("google_identity_uid", "tenant_id")},
            },
        ),
    ]
